### ISSUE TITLE
Add Method to dbConnection class in Database Package to run direct SQL query.

### ISSUE THREAD

**Issue by Bhavya0304** [Bhavya0304/Chat-Room-With-Java#1]
## New Feature 
**Add a method that can be used to run direct SQL queries with parameters**

## Location
[-] dbConnection Class in dbConnection.java file in src->Libraries->Database

**Comment by Hi10khatri** [comment]
Please assign me this issue.

**Comment by Bhavya0304** [comment]
Sure! Best of luck.

**Comment by arth2002** [comment]
Hey @Bhavya0304 
I wan to work on this Issue
Can you please assign me?

**Comment by Bhavya0304** [comment]
Sure!

**Comment by singloon** [comment]
Which db query do you want it for? If you want params then we need to set the specific args in the prepare statement?
